services:
  - type: web
    name: image-background-remover-backend
    env: node
    rootDir: BG-Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        value: mongodb+srv://selvakumar0000001111:Selva2004.@cluster0.mongodb.net/bg_remove?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: qwertsdhfgskjdnkolskskss
      - key: CLIPDROP_API_KEY
        value: 43ed14672b51e9b46c80397aaf4f15bb6a22c6a874a1888138ac3c69836e73f56f5ade9cf45c26cbc8a07c09aa2b2ab9
